CREATE TABLE IF NOT EXISTS fund_performance_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('profit', 'land_growth')),
    amount NUMERIC NOT NULL,
    date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_by TEXT -- email of the CEO/Admin
);

-- Enable Row Level Security (RLS)
ALTER TABLE fund_performance_history ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
DROP POLICY IF EXISTS "Enable read access for all users" ON fund_performance_history;
CREATE POLICY "Enable read access for all users" ON fund_performance_history
    FOR SELECT USING (true);

-- Allow insert access to everyone (Required for backend to log history)
DROP POLICY IF EXISTS "Enable insert access for all users" ON fund_performance_history;
CREATE POLICY "Enable insert access for all users" ON fund_performance_history
    FOR INSERT WITH CHECK (true);
